DevDay.Quiz/Models/Question.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace DevDay.Quiz.Models
{
    [Table("Questions")]
    public class Question
    {
        public int Id { get; set; }
        [Display(Name = "Question Text")]
        public string Text { get; set; }
        public virtual ICollection<Answer> Answers { get; set; }
        [Display(Name = "Order")]
        public int SortOrder { get; set; }
        public int SessionId { get; set; }
        public virtual Session Session { get; set; }
    }
}

DevDay.Quiz/Controllers/AnswersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DevDay.Quiz.Models;

namespace DevDay.Quiz.Controllers
{
    public class AnswersController : Controller
    {
        private QuizContext db = new QuizContext();

        //
        // GET: /Answers/

        public ActionResult Index()
        {
            var answers = db.Answers.Include(a => a.Question);
            return View(answers.ToList());
        }

        //
        // GET: /Answers/Create

        public ActionResult Create()
        {
            ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Text");
            return View();
        }

        //
        // POST: /Answers/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Answer answer)
        {
            if (ModelState.IsValid)
            {
                db.Answers.Add(answer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Text", answer.QuestionId);
            return View(answer);
        }

        //
        // GET: /Answers/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Answer answer = db.Answers.Find(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Text", answer.QuestionId);
            return View(answer);
        }

        //
        // POST: /Answers/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Answer answer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(answer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Text", answer.QuestionId);
            return View(answer);
        }

        //
        // GET: /Answers/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Answer answer = db.Answers.Find(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            return View(answer);
        }

        //
        // POST: /Answers/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Answer answer = db.Answers.Find(id);
            db.Answers.Remove(answer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

DevDay.Quiz/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DevDay.Quiz.Models;

namespace DevDay.Quiz.Controllers
{
    public class QuestionsController : Controller
    {
        private QuizContext db = new QuizContext();

        //
        // GET: /Questions/

        public ActionResult Index()
        {
            var questions = db.Questions.Include(q => q.Session);
            return View(questions.OrderBy(q => q.SortOrder).ToList());
        }

        //
        // GET: /Questions/Create

        public ActionResult Create()
        {
            ViewBag.SessionId = new SelectList(db.Sessions, "Id", "Text");
            return View();
        }

        //
        // POST: /Questions/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Question question)
        {
            if (ModelState.IsValid)
            {
                db.Questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SessionId = new SelectList(db.Sessions, "Id", "Text", question.SessionId);
            return View(question);
        }

        //
        // GET: /Questions/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            ViewBag.SessionId = new SelectList(db.Sessions, "Id", "Text", question.SessionId);
            return View(question);
        }

        //
        // POST: /Questions/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Question question)
        {
            if (ModelState.IsValid)
            {
                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SessionId = new SelectList(db.Sessions, "Id", "Text", question.SessionId);
            return View(question);
        }

        //
        // GET: /Questions/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        //
        // POST: /Questions/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.Questions.Find(id);
            db.Questions.Remove(question);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

DevDay.Quiz/Views/Questions/Create.cshtml
@model DevDay.Quiz.Models.Question

<div class="row">
	<div class="large-8 columns">
	    <div class="large-12 columns">
	    @{
            ViewBag.Title = "Create Question";
        }

        <h2>Create</h2>

        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <fieldset class="radius grey-bground">
                <legend>Question</legend>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Text)
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.Text, new {@class = "radius"})
                    @Html.ValidationMessageFor(model => model.Text)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.SortOrder)
                    <p class="smallText">Questions from parallel sessions need to have the same order</p>
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.SortOrder, new {@class = "radius"})
                    @Html.ValidationMessageFor(model => model.SortOrder)
                </div>
                
                <div class="editor-label">
                    @Html.LabelFor(model => model.SessionId, "Session")
                </div>
                <div class="editor-field">
                    @Html.DropDownList("SessionId", String.Empty)
                    @Html.ValidationMessageFor(model => model.SessionId)
                </div>

                <p>
                    <input type="submit"  class="small button" value="Create" />
                </p>
            </fieldset>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>        

	    </div>
	</div>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DevDay.Quiz/Views/Questions/Delete.cshtml
@model DevDay.Quiz.Models.Question

<div class="row">
	<div class="large-8 columns">
	    <div class="large-12 columns">
	        
            @{
                ViewBag.Title = "Delete Question";
            }

            <h2>Delete</h2>

            <h3>Are you sure you want to delete this?</h3>
            <fieldset class="radius grey-bground">
                <legend>Question</legend>

                <div class="display-label">
                     @Html.DisplayNameFor(model => model.Text)
                </div>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Text)
                </div>

                <div class="display-label">
                     @Html.DisplayNameFor(model => model.SortOrder)
                </div>
                <div class="display-field">
                    @Html.DisplayFor(model => model.SortOrder)
                </div>

                <div class="display-label">
                     @Html.DisplayNameFor(model => model.Session.Title)
                </div>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Session.Title)
                </div>

            </fieldset>
            @using (Html.BeginForm()) {
                @Html.AntiForgeryToken()
                <p>
                    <input type="submit" class="small button" value="Delete" /> |
                    @Html.ActionLink("Back to List", "Index")
                </p>
            }
	    </div>
	</div>
</div>

DevDay.Quiz/Views/Questions/Edit.cshtml
@model DevDay.Quiz.Models.Question

<div class="row">
	<div class="large-8 columns">
	    <div class="large-12 columns">
	        
        @{
            ViewBag.Title = "Edit Question";
        }

        <h2>Edit</h2>

        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <fieldset class="radius dark-grey-bground">
                <legend>Question</legend>

                @Html.HiddenFor(model => model.Id)

                <div class="editor-label">
                    @Html.LabelFor(model => model.Text)
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.Text, new { @class = "radius" })
                    @Html.ValidationMessageFor(model => model.Text)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.SortOrder)
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.SortOrder, new { @class = "radius" })
                    @Html.ValidationMessageFor(model => model.SortOrder)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.SessionId, "Session")
                </div>
                <div class="editor-field">
                    @Html.DropDownList("SessionId", String.Empty)
                    @Html.ValidationMessageFor(model => model.SessionId)
                </div>

                <p>
                    <input type="submit" class="small button" value="Save" />
                </p>
            </fieldset>
        }
            
	        <fieldset class="radius dark-grey-bground">
	        <legend>Answers</legend>
            <p>
                @Html.ActionLink("Add Answer", "Create", "Answers", null, new {@class = "small button"})
            </p>
	            @foreach (var answer in Model.Answers)
	            {
	                string weight = null;
	                if (!answer.Correct)
	                {
	                    weight = "normal";
	                }
	                <div class="accordion">
	                    <h4 class="radius @weight grey-bground">@Html.Raw(answer.Text)</h4>
	                    <div class="acc-content radius grey-bground">
	                        <div class="display-label">
	                            @Html.DisplayNameFor(a => answer.SortOrder) : @Html.DisplayFor(a => answer.SortOrder)
	                        </div>
	                        <div class="display-label">
	                            @Html.DisplayNameFor(a => answer.Correct) : @answer.Correct
	                        </div>
	                        <div class="display-field">
	                            @Html.ActionLink("Edit", "Edit", "Answers", new { id=answer.Id }, null) 
	                            |
	                            @Html.ActionLink("Delete", "Delete", "Answers", new { id=answer.Id }, null)
	                        </div>
	                    </div>
	                </div>
                }
            </fieldset>

	        <div>
	            @Html.ActionLink("Back to List", "Index")
	        </div>

	    </div>
	</div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DevDay.Quiz/Views/Questions/Index.cshtml
@model IEnumerable<DevDay.Quiz.Models.Question>

<div class="row">
	<div class="large-8 columns">
	    <div class="large-12 columns">
	        
            @{
                ViewBag.Title = "Questions";
            }

            <h2>Questions</h2>

	        <p>
	            @Html.ActionLink("Create New", "Create", null, new {@class = "small button"})
	        </p>

            @foreach (var item in Model)
	        {
	            <div class="accordion">
	                <h4 class="radius normal dark-grey-bground">@item.Text</h4>
	                <div class="acc-content radius grey-bground">
	                    <div class="display-label">
	                        @Html.DisplayNameFor(i => i.Answers) : @item.Answers.Count
	                    </div>	                    
                        <div class="display-label">
                            @Html.DisplayNameFor(i => i.SortOrder) : @item.SortOrder
	                    </div>
                        <div class="display-label">
                             @Html.DisplayNameFor(model => model.Session.Title) : @item.Session.Title
                        </div>
                        <div class="display-field">
                            @Html.DisplayNameFor(model => model.Session.Speaker) : @item.Session.Speaker
                        </div>
	                    <div class="display-field">
                        @Html.ActionLink("Edit", "Edit", new { id=item.Id }) 
                        |
                        @Html.ActionLink("Delete", "Delete", new { id=item.Id })
	                    </div>
	                </div>
	            </div>
            }

	    </div>
	</div>
</div>